import type { Translation } from './en';

const ko: Translation = {
  lang: { code: 'ko', name: '한국어', flag: '🇰🇷', dir: 'ltr' },
  nav: { platform: '플랫폼', industries: '산업', capabilities: '기능', roadmap: '로드맵', security: '보안', contact: '문의', bookDemo: '데모 예약' },
  hero: { eyebrow: 'AI 기반 물리 보안 인텔리전스', title1: '모든 카메라를 지켜보는 AI', title2: '팀이 직접 지켜보지 않아도 됩니다.', lede: 'Bimeon은 기존 보안 카메라를 실시간 인텔리전스 시스템으로 전환합니다. 모든 영상을 지속적으로 분석하고 관심 인물을 식별하며 중요한 순간에 팀에 알려드립니다.', bookDemo: '데모 예약', watchOverview: '플랫폼 소개 보기', note: '안전을 타협할 수 없는 조직을 위해 설계되었습니다.', liveAlert: '실시간 알림', unknownPerson: '미확인 인물 감지', alertLocation: '북쪽 입구 · 2분 전', high: '높음', continuousMonitoring: '연속 모니터링', activeCameras: '활성 카메라', eventsToday: '오늘의 이벤트', peopleRecognized: '인식된 인물', facilities: '시설' },
  trust: { title: '전 세계 보안 리더들이 신뢰합니다', enterpriseReady: '엔터프라이즈 지원', realtimeIntelligence: '실시간 인텔리전스', scalableArchitecture: '확장 가능한 아키텍처', criticalEnvironments: '중요 환경' },
  problem: { kicker: '문제', title1: '카메라는 모든 것을 봅니다.', title2: '팀이 모두 볼 수는 없습니다.', cards: [{ title: '카메라는 너무 많고 사람은 부족합니다', text: '보안팀은 수백 개의 영상을 동시에 모니터링할 수 없습니다. 중요한 이벤트를 놓치게 됩니다.' }, { title: '느린 대응 시간', text: '사고를 발견했을 때는 대응할 수 있는 시간이 이미 지나간 경우가 많습니다.' }, { title: '조사에 몇 시간이 걸립니다', text: '영상을 찾는 일은 수동적이고 느리며 비용이 큽니다. 답은 너무 늦게 도착합니다.' }] },
  comparison: { kicker: '차이점', title1: 'Bimeon 이전과', title2: 'Bimeon 이후.', without: 'BIMEON 없이', with: 'BIMEON과 함께', withoutItems: ['제한된 영상 수동 모니터링', '실시간 중요 이벤트 누락', '몇 시간 또는 며칠이 걸리는 조사', '시설 간 통합된 가시성 부족', '사후 대응 중심', '제한적인 상황 인식'], withItems: ['AI가 모든 카메라를 동시에 모니터링', '중요한 순간의 실시간 알림', '몇 초 만에 자연어 검색', '모든 시설을 한 화면에서 확인', '선제적 위협 감지', '완전한 상황 인식'] },
  solution: { kicker: '솔루션', title1: '기존 카메라를', title2: '실시간 인텔리전스로 전환하세요.', lede: 'Bimeon은 이미 보유한 카메라와 함께 작동합니다. 새 하드웨어도, 전면 교체도 필요 없습니다. 인텔리전스만 더하세요.', cards: [{ title: '기존 카메라와 작동', text: '현재 인프라를 연결하세요. Bimeon은 하드웨어가 아닌 인텔리전스를 추가합니다.' }, { title: '실시간 인식', text: '관심 인물이 나타나는 순간 모든 영상에서 식별합니다.' }, { title: '즉시 알림', text: '중요할 때 알림을 받으세요. 위협 수준별 우선순위가 핵심에 집중하게 합니다.' }, { title: '자연어 검색', text: '일상적인 말로 질문하고 몇 초 만에 답을 찾으세요.' }, { title: '전체 이벤트 기록', text: '모든 이벤트를 기록하고 시간과 위치별로 검색하고 추적할 수 있습니다.' }, { title: '간편한 배포', text: '카메라를 연결하고 인물을 등록해 빠르게 모니터링을 시작하세요.' }] },
  capabilities: { kicker: '기능', title1: '팀에 필요한 모든 것.', title2: '불필요한 것은 없습니다.', lede: '중요한 환경에서 운영되는 전문 보안팀을 위한 완전한 플랫폼입니다.', items: [{ title: '실시간 얼굴 인식', detail: '환경을 이동하는 관심 인물을 식별합니다.' }, { title: '미확인 인물 감지', detail: '모니터링 공간에 인식되지 않은 사람이 들어오면 알려줍니다.' }, { title: '위협 분류', detail: '낮음, 중간, 높음, 심각 이벤트를 즉시 우선순위화합니다.' }, { title: '자연어 검색', detail: '보안 기록에 질문하고 답을 찾습니다.' }, { title: '기록 타임라인', detail: '시간, 카메라, 위치별 활동을 몇 초 만에 추적합니다.' }, { title: '무제한 카메라 모니터링', detail: '모든 카메라와 알림, 프로필을 한곳에서 관리합니다.' }, { title: '얼굴 등록', detail: '웹캠 또는 이미지 업로드로 인물을 등록합니다.' }, { title: '고급 필터', detail: '이름, 분류, 날짜, 시간, 카메라 및 인식 상태로 필터링합니다.' }, { title: '확장 가능한 인프라', detail: '엔터프라이즈급 아키텍처로 여러 시설에 배포합니다.' }, { title: '인물 프로필 관리', detail: '승인, 제한, 주의, 실종 인물을 관리합니다.' }, { title: '즉시 알림', detail: '중요한 순간에 적절한 사람에게 실시간 알림을 전달합니다.' }, { title: '엔터프라이즈 지원', detail: '중요 환경이 요구하는 표준과 책임, 통제를 위해 구축되었습니다.' }] },
  industries: { kicker: '산업', title1: '인텔리전스가', title2: '보호가 되는 곳.', lede: '단일 캠퍼스부터 전국 단위의 분산 운영까지, Bimeon은 책임의 규모에 맞춰 확장됩니다.', learnMore: '자세히 보기', items: [{ name: '교육', text: '항상 시선을 유지하는 인텔리전스로 학생과 교직원, 캠퍼스를 보호합니다.' }, { name: '의료', text: '의료팀과 보안팀이 모든 중요한 순간을 함께 확인합니다.' }, { name: '공항', text: '복잡하고 유동적인 환경에서 상황 인식을 유지합니다.' }, { name: '정부', text: '책임감 있는 실시간 인텔리전스로 시설과 사람을 보호합니다.' }, { name: '제조', text: '지역사회와 경제가 의존하는 장소를 더 안전하게 만듭니다.' }, { name: '경기장', text: '모든 시설과 팀, 현장으로 보안 운영을 확장합니다.' }] },
  howItWorks: { kicker: '작동 방식', title: '네 단계로 운영을 시작하세요.', steps: [{ title: '기존 카메라 연결', text: 'Bimeon은 현재 카메라 인프라에 통합됩니다. 전면 교체가 필요 없습니다.' }, { title: '인물 등록', text: '웹캠이나 이미지 업로드로 승인, 제한, 주의 인물을 등록합니다.' }, { title: 'AI가 모든 것을 모니터링', text: '모든 영상을 지속 분석해 인물을 식별하고 위협을 실시간으로 감지합니다.' }, { title: '실시간 알림 수신', text: '가장 중요한 순간에 즉시 알림을 받으세요. 확신을 갖고 대응할 수 있습니다.' }] },
  benefits: { kicker: '엔터프라이즈 혜택', title1: '조직이', title2: 'Bimeon을 선택하는 이유.', lede: '보안은 기능이 아니라 기반입니다. Bimeon은 중요 환경이 요구하는 기준을 위해 만들어졌습니다.', bookDemo: '데모 예약', items: ['대응 시간 단축', '상황 인식 향상', '기존 카메라 인프라 활용', '모니터링 중앙화', '조사 속도 향상', '운영 효율 개선', '여러 시설로 확장'] },
  roadmap: { kicker: '출시 예정', title: '앞으로의 계획.', lede: 'Bimeon은 계속 확장됩니다. 플랫폼 로드맵의 다음 기능을 확인하세요.', soon: '출시 예정', items: [{ title: '카메라 간 자동 추적', detail: '시설의 모든 카메라에서 관심 인물을 끊김 없이 추적합니다.' }, { title: '알림 영상 재생', detail: '알림을 발생시킨 정확한 순간의 영상을 즉시 재생합니다.' }, { title: '무기 감지', detail: '카메라에 나타나는 순간 총기와 무기를 식별합니다.' }, { title: '화재 및 연기 감지', detail: '확산되기 전에 화재와 연기를 조기에 감지합니다.' }, { title: '쓰러짐 감지', detail: '사람이 넘어지거나 움직이지 못하는 상태를 자동으로 감지합니다.' }, { title: '공격적 행동 감지', detail: '사건이 되기 전에 행동의 고조를 식별합니다.' }, { title: '전체 감사 로그', detail: '변조 방지 감사 기록으로 완전한 책임성을 제공합니다.' }, { title: '역할 기반 권한', detail: '팀과 현장, 기능 전반에 세밀한 접근 제어를 제공합니다.' }, { title: '위험 점수', detail: '모든 인물과 이벤트에 AI 기반 위험 평가를 제공합니다.' }, { title: '사건 보고서', detail: '한 번의 클릭으로 상세 사건 보고서를 생성합니다.' }, { title: '엔터프라이즈 API', detail: 'Bimeon 인텔리전스를 기존 시스템에 통합합니다.' }, { title: '카메라 간 추적', detail: '시설 전체의 움직임을 실시간으로 추적합니다.' }] },
  security: { kicker: '보안', title1: '보안은 기능이 아닙니다.', title2: '기반입니다.', lede: 'Bimeon은 중요 환경이 요구하는 표준과 책임, 통제를 위해 설계되었습니다.', items: [{ title: '암호화된 데이터', detail: '모든 데이터는 전송 중과 저장 시 암호화됩니다.' }, { title: '역할 기반 접근', detail: '적절한 사람에게 적절한 정보를 제공합니다.' }, { title: '감사 로그', detail: '모든 이벤트와 행동에 대한 책임성을 확보합니다.' }, { title: '개인정보 보호 우선 아키텍처', detail: '책임 있는 인텔리전스를 위한 전용 제어 기능입니다.' }, { title: '컴플라이언스 지원', detail: '엔터프라이즈 보안 표준을 충족하도록 설계되었습니다.' }, { title: '기존 카메라와 호환', detail: '현재 인프라에 배포할 수 있습니다.' }] },
  finalCta: { kicker: '더 명확한 전진', title1: '가장', title2: '중요한 것을 지키세요.', lede: 'Bimeon이 조직을 위해 할 수 있는 일을 확인하세요.', bookDemo: '데모 예약' },
  footer: { tagline1: '중요한 장소를 위한', tagline2: '실시간 인텔리전스.', explore: '탐색', company: '회사', contact: '문의', requestDemo: '데모 요청', privacyPolicy: '개인정보 처리방침', terms: '약관', copyright: '© 2024 Bimeon Technologies, Inc.', domain: 'bimeon.pro' },
  modal: { kicker: '대화 시작하기', title1: '귀사의 환경에서', title2: 'Bimeon을 확인하세요.', lede: '운영에 대해 간단히 알려주시면 저희 팀이 연락드리겠습니다.', workEmail: '회사 이메일', emailPlaceholder: 'you@organization.com', organization: '조직', orgPlaceholder: '조직 이름', industry: '산업', industries: ['교육', '의료', '공항', '정부', '제조', '경기장', '기타'], submitting: '제출 중...', requestDemo: '데모 요청', bySubmitting: '제출하면 Bimeon의 연락에 동의하는 것입니다.', successTitle: '요청이 접수되었습니다.', successText: '감사합니다. 영업일 기준 하루 안에 데모 일정을 위해 연락드리겠습니다.', done: '완료', error: '문제가 발생했습니다. 다시 시도해 주세요.' },
  searchExamples: ['오후 2시에서 4시 사이의 제한 인물', '오늘 John은 어디에 있었나요?', '어제의 미확인 인물', '이번 주 실종자'],
};
export default ko;
