import type { Translation } from './en';

const zh: Translation = {
  lang: { code: 'zh', name: '简体中文', flag: '🇨🇳', dir: 'ltr' },
  nav: { platform: '平台', industries: '行业', capabilities: '功能', roadmap: '路线图', security: '安全', contact: '联系我们', bookDemo: '预约演示' },
  hero: { eyebrow: 'AI 驱动的实体安全智能', title1: 'AI 监控每一台摄像机', title2: '让您的团队无需时刻盯守。', lede: 'Bimeon 将现有的安防摄像机转化为实时智能系统，持续分析每一路视频，识别关注人员，并在关键时刻向团队发出警报。', bookDemo: '预约演示', watchOverview: '观看平台概览', note: '为安全不容妥协的组织而打造。', liveAlert: '实时警报', unknownPerson: '检测到未知人员', alertLocation: '北门 · 2 分钟前', high: '高', continuousMonitoring: '持续监控', activeCameras: '运行中的摄像机', eventsToday: '今日事件', peopleRecognized: '已识别人次', facilities: '设施' },
  trust: { title: '全球安全领域领导者信赖', enterpriseReady: '企业级就绪', realtimeIntelligence: '实时智能', scalableArchitecture: '可扩展架构', criticalEnvironments: '关键环境' },
  problem: { kicker: '问题', title1: '您的摄像机看得见一切。', title2: '但团队无法同时关注。', cards: [{ title: '摄像机太多，人手太少', text: '安全团队无法同时监控数百路视频，关键事件因此可能被错过。' }, { title: '响应速度缓慢', text: '当事件被发现时，最佳响应窗口往往已经关闭。' }, { title: '调查耗时数小时', text: '检索录像依赖人工，缓慢且昂贵，答案总是来得太晚。' }] },
  comparison: { kicker: '差异', title1: '使用 Bimeon 之前', title2: '与使用 Bimeon 之后。', without: '没有 BIMEON', with: '使用 BIMEON', withoutItems: ['手动监控有限的视频流', '实时错过关键事件', '调查需要数小时甚至数天', '不同地点之间缺乏集中视野', '被动响应而非主动预防', '态势感知能力有限'], withItems: ['AI 同时监控每一台摄像机', '在关键时刻实时发出警报', '几秒内完成自然语言搜索', '统一查看所有设施', '主动发现潜在威胁', '完整的态势感知'] },
  solution: { kicker: '解决方案', title1: '让现有摄像机', title2: '升级为实时智能。', lede: 'Bimeon 兼容您已有的摄像机，无需新增硬件，无需整体更换，直接获得智能能力。', cards: [{ title: '兼容现有摄像机', text: '连接现有基础设施，Bimeon 增加的是智能，而不是硬件。' }, { title: '实时识别', text: '关注人员一出现，就能在每一路视频中被识别。' }, { title: '即时警报', text: '重要事件及时通知，威胁等级排序让注意力始终聚焦重点。' }, { title: '自然语言搜索', text: '用日常语言提问，几秒而非数小时找到答案。' }, { title: '完整事件历史', text: '每个事件都可记录、搜索，并按时间和地点追踪。' }, { title: '快速部署', text: '连接摄像机、登记人员，快速开始监控。' }] },
  capabilities: { kicker: '功能', title1: '团队所需的一切。', title2: '没有多余负担。', lede: '为关键环境中的专业安全团队打造的完整平台。', items: [{ title: '实时人脸识别', detail: '识别在环境中移动的关注人员。' }, { title: '未知人员检测', detail: '监测空间中出现未识别人员时立即知晓。' }, { title: '威胁分类', detail: '即时区分低、中、高和严重事件。' }, { title: '自然语言搜索', detail: '向安全历史提问并找到答案。' }, { title: '历史时间线', detail: '数秒内追踪不同时间、摄像机和地点的活动。' }, { title: '无限摄像机监控', detail: '在一个清晰的界面中集中管理摄像机、警报和档案。' }, { title: '人脸登记', detail: '通过摄像头或图片上传登记人员。' }, { title: '高级筛选', detail: '按姓名、类别、日期、时间、摄像机和识别状态筛选。' }, { title: '可扩展基础设施', detail: '以企业级架构部署到多个设施。' }, { title: '人员档案管理', detail: '管理授权、受限、标记和失踪人员。' }, { title: '即时通知', detail: '在关键时刻将实时警报发送给正确的人。' }, { title: '企业级就绪', detail: '满足关键环境对标准、问责和控制的要求。' }] },
  industries: { kicker: '行业', title1: '让智能', title2: '成为保护。', lede: '从单一校园到分布式全国运营，Bimeon 随您的责任规模共同成长。', learnMore: '了解更多', items: [{ name: '教育', text: '用始终保持警觉的智能保护学生、教职员工和校园。' }, { name: '医疗', text: '让医疗和安全团队共享每个关键时刻的视野。' }, { name: '机场', text: '在复杂、高流量环境中保持态势感知。' }, { name: '政府', text: '以负责任的实时智能保护设施和人员。' }, { name: '制造业', text: '加强社区和经济赖以发展的场所。' }, { name: '体育场馆', text: '将安全运营延伸到每个地点、团队和设施。' }] },
  howItWorks: { kicker: '工作方式', title: '四步即可投入运行。', steps: [{ title: '连接现有摄像机', text: 'Bimeon 集成现有摄像机基础设施，无需整体更换。' }, { title: '登记人员', text: '通过摄像头或图片上传登记授权、受限和标记人员。' }, { title: 'AI 监控一切', text: 'Bimeon 持续分析每一路视频，实时识别人员并发现威胁。' }, { title: '接收实时警报', text: '在最重要的时刻收到即时通知，充满信心地采取行动。' }] },
  benefits: { kicker: '企业优势', title1: '为什么组织', title2: '选择 Bimeon。', lede: '安全不是一个功能，而是基础。Bimeon 为关键环境所要求的标准而打造。', bookDemo: '预约演示', items: ['缩短响应时间', '提升态势感知', '利用现有摄像机基础设施', '集中监控', '加快调查', '提升运营效率', '扩展至多个设施'] },
  roadmap: { kicker: '即将推出', title: '未来路线。', lede: 'Bimeon 持续扩展，以下是平台路线图中的下一步。', soon: '即将推出', items: [{ title: '摄像机之间自动追踪', detail: '跨设施摄像机无缝跟踪关注人员。' }, { title: '警报视频回放', detail: '即时回放触发警报的准确视频时刻。' }, { title: '武器检测', detail: '武器出现在画面中时立即识别。' }, { title: '火灾和烟雾检测', detail: '在火灾和烟雾扩散前及早发现。' }, { title: '人员倒地检测', detail: '自动检测人员跌倒或失去行动能力。' }, { title: '攻击性行为检测', detail: '在事件发生前发现行为升级。' }, { title: '完整审计日志', detail: '以防篡改的审计记录实现完整问责。' }, { title: '基于角色的权限', detail: '跨团队、地点和职能进行精细访问控制。' }, { title: '风险评分', detail: '为每个人员和事件提供 AI 风险评估。' }, { title: '事件报告', detail: '一键生成详细的事件报告。' }, { title: '企业 API', detail: '将 Bimeon 智能集成到现有系统。' }, { title: '摄像机间追踪', detail: '实时追踪整个设施中的人员移动。' }] },
  security: { kicker: '安全', title1: '安全不是一个功能。', title2: '而是基础。', lede: 'Bimeon 按照关键环境所需的标准、问责和控制进行设计。', items: [{ title: '数据加密', detail: '所有数据在传输和存储时均加密。' }, { title: '基于角色的访问', detail: '让正确的人获得正确的信息。' }, { title: '审计日志', detail: '记录每一个事件和操作，实现完整问责。' }, { title: '隐私优先架构', detail: '为负责任的智能打造专用控制措施。' }, { title: '为合规而设计', detail: '按企业安全标准进行设计。' }, { title: '兼容现有摄像机', detail: '部署在现有基础设施上。' }] },
  finalCta: { kicker: '更清晰的前进方式', title1: '保护真正', title2: '重要的一切。', lede: '了解 Bimeon 能为您的组织带来什么。', bookDemo: '预约演示' },
  footer: { tagline1: '为重要场所提供', tagline2: '实时智能。', explore: '探索', company: '公司', contact: '联系我们', requestDemo: '申请演示', privacyPolicy: '隐私政策', terms: '条款', copyright: '© 2024 Bimeon Technologies, Inc.', domain: 'bimeon.pro' },
  modal: { kicker: '开始交流', title1: '在您的环境中', title2: '体验 Bimeon。', lede: '简单介绍您的业务，我们的团队会与您联系。', workEmail: '工作邮箱', emailPlaceholder: 'you@organization.com', organization: '组织', orgPlaceholder: '组织名称', industry: '行业', industries: ['教育', '医疗', '机场', '政府', '制造业', '体育场馆', '其他'], submitting: '提交中...', requestDemo: '申请演示', bySubmitting: '提交即表示您同意 Bimeon 与您联系。', successTitle: '已收到申请。', successText: '感谢您。我们的团队将在一个工作日内联系您安排演示。', done: '完成', error: '出现问题，请重试。' },
  searchExamples: ['下午 2 点至 4 点的受限人员', '约翰今天在哪里？', '昨天的未知人员', '本周的失踪人员'],
};
export default zh;
